apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData: SECRET=jwt-veryhard-secret
  CONNECTION_STRING=mongodb+srv://ffekirnew:KA8VG3Id6rU242xE@cluster0.ybkwa1w.mongodb.net/
  DB_NAME=py-microservices-auth
type: Opaque
